name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v0.1)'
        required: true
        default: 'v0.1'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Skip analysis and tests for release build
      - name: Build web
        run: flutter build web --release --no-tree-shake-icons

      - name: Build Android APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Zip Web Build
        run: |
          cd build
          zip -r web-build.zip web/

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: |
            ./build/web-build.zip
            ./build/app/outputs/flutter-apk/app-release.apk
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
